version: '3.5'
services:
  api1:
    image: kotenko2002/api1
    container_name: api1
    ports: 
      - '5000:5000'
    restart: unless-stopped
    networks:
      - studydocker
  api2:
    image: kotenko2002/api2
    container_name: api2
    ports: 
      - '7000:7000'
    restart: unless-stopped
    networks:
      - studydocker
networks:
  studydocker:
    name: studydocker
    driver: bridge